-- Supabase SQL Editor에 붙여넣고 실행하세요.
-- 주의: 아래 drop table은 저장된 내용을 모두 지웁니다. 처음 설치할 때만 사용하세요.

drop table if exists portfolio;

-- 1. 포트폴리오 데이터를 담는 테이블 (내용 전체를 JSON 한 덩어리로 보관)
create table portfolio (
  id bigint primary key generated by default as identity,
  content jsonb
);

alter table portfolio enable row level security;

-- 2. 권한 설정
--    누구나 "읽기"만 할 수 있게 하고, "쓰기"는 서버(서비스 롤 키)만 하도록 막습니다.
--    서비스 롤 키는 RLS를 우회하므로 별도 정책이 필요 없습니다.
create policy "Public read"
on portfolio for select
using (true);

-- 3. 초기 행 생성 (앱은 항상 id = 1 행을 사용합니다)
insert into portfolio (id, content)
values (1, '{}');

--------------------------------------------------------------------------------
-- 4. 사진 저장소 (기록에 올리는 현장 사진이 여기에 저장됩니다)
--    이미 만들어져 있으면 아무 일도 하지 않으므로 다시 실행해도 안전합니다.
insert into storage.buckets (id, name, public)
values ('portfolio-media', 'portfolio-media', true)
on conflict (id) do nothing;

-- 방문자는 사진을 볼 수만 있고, 올리기·지우기는 서버(서비스 롤 키)만 할 수 있습니다.
create policy "Public read media"
on storage.objects for select
using (bucket_id = 'portfolio-media');

--------------------------------------------------------------------------------
-- 5. 관리자 로그인 실패 기록
--    (이 항목만 따로 복사해 실행해도 안전합니다. 기존 데이터를 지우지 않습니다.)
--
--    Vercel 같은 서버리스 환경은 요청마다 다른 인스턴스가 처리할 수 있어서,
--    서버 메모리에만 둔 실패 횟수는 쉽게 사라집니다(차단을 우회할 수 있습니다).
--    그래서 실패 기록을 이 표에 남겨 모든 인스턴스가 같은 기록을 보게 합니다.
create table if not exists admin_login_attempts (
  ip_hash text primary key,
  failed_count integer not null default 0,
  first_failed_at timestamptz not null default now(),
  blocked_until timestamptz
);

alter table admin_login_attempts enable row level security;

-- 이 표에는 정책을 하나도 만들지 않습니다.
-- 그래서 공개(anon) 키로는 읽기도 쓰기도 모두 막히고,
-- RLS를 우회하는 서비스 롤 키(서버)만 기록을 남길 수 있습니다.
-- IP는 서버 전용 키로 HMAC-SHA256 해싱해 저장하므로 원래 주소는 남지 않습니다.
--
-- 서비스 롤 키(SUPABASE_SERVICE_ROLE_KEY)가 없거나 이 표를 만들지 않으면
-- 로그인은 그대로 되지만, 차단은 예전처럼 인스턴스별 메모리로만 유지됩니다.

--------------------------------------------------------------------------------
-- ⚠️ 중요: 위 "Public read" 정책만 두면 쓰기가 막히므로,
--    배포 환경(Vercel 등)에 서버 전용 환경변수를 반드시 추가해야 합니다.
--
--      SUPABASE_SERVICE_ROLE_KEY = (Supabase 대시보드 > Project Settings > API > service_role)
--
--    이 값은 NEXT_PUBLIC_ 접두사를 붙이면 안 됩니다. 브라우저로 노출되면
--    누구나 데이터를 지울 수 있습니다.
--
--    아직 서비스 롤 키를 설정하지 않았다면, 임시로 아래 정책을 함께 실행해
--    기존처럼 anon 키로도 쓰기가 되게 할 수 있습니다. (보안상 권장하지 않습니다)
--
--      create policy "Temporary anon write"
--      on portfolio for all
--      using (true) with check (true);
--------------------------------------------------------------------------------
