-- Supabase SQL Editor에 붙여넣고 실행하세요.
-- 주의: 아래 drop table은 저장된 내용을 모두 지웁니다. 처음 설치할 때만 사용하세요.

drop table if exists portfolio;

-- 1. 포트폴리오 데이터를 담는 테이블 (내용 전체를 JSON 한 덩어리로 보관)
create table portfolio (
  id bigint primary key generated by default as identity,
  content jsonb
);

alter table portfolio enable row level security;

-- 2. 권한 설정
--    누구나 "읽기"만 할 수 있게 하고, "쓰기"는 서버(서비스 롤 키)만 하도록 막습니다.
--    서비스 롤 키는 RLS를 우회하므로 별도 정책이 필요 없습니다.
create policy "Public read"
on portfolio for select
using (true);

-- 3. 초기 행 생성 (앱은 항상 id = 1 행을 사용합니다)
insert into portfolio (id, content)
values (1, '{}');

--------------------------------------------------------------------------------
-- ⚠️ 중요: 위 "Public read" 정책만 두면 쓰기가 막히므로,
--    배포 환경(Vercel 등)에 서버 전용 환경변수를 반드시 추가해야 합니다.
--
--      SUPABASE_SERVICE_ROLE_KEY = (Supabase 대시보드 > Project Settings > API > service_role)
--
--    이 값은 NEXT_PUBLIC_ 접두사를 붙이면 안 됩니다. 브라우저로 노출되면
--    누구나 데이터를 지울 수 있습니다.
--
--    아직 서비스 롤 키를 설정하지 않았다면, 임시로 아래 정책을 함께 실행해
--    기존처럼 anon 키로도 쓰기가 되게 할 수 있습니다. (보안상 권장하지 않습니다)
--
--      create policy "Temporary anon write"
--      on portfolio for all
--      using (true) with check (true);
--------------------------------------------------------------------------------
